openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret_api API"
  description: "paw_arbeidssokerregisteret_api API"
  version: "1.0.0"
servers:
- url: "https://paw_arbeidssokerregisteret_api"
paths:
  /api/v1/arbeidssoker/perioder:
    post:
      description: ""
      parameters:
      - name: "fraOgMed"
        in: "query"
        required: false
        schema:
          type: "string"
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/EksternRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Parameter fraOgMed være satt med dd-mm-yyyy"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Arbeidssokerperiode"
  /internal/isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /internal/isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
  /internal/metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    EksternRequest:
      type: "object"
      properties:
        foedselsnummer:
          type: "string"
    Arbeidssokerperiode:
      type: "object"
      properties:
        fraOgMed:
          type: "string"
          format: "date-time"
        tilOgMed:
          type: "string"
          format: "date-time"