version: '3.9'

services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.6
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      JSON_CONFIG: >
        {
          "interactiveLogin": true,
          "httpServer": "NettyWrapper",
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 15780000,
              "requestMappings": [
                {
                  "requestParam": "scope",
                  "match": "openid somescope",
                  "claims": {
                    "sub": "admin@paw-arbeidssokerregisteret-api",
                    "aud": ["paw-arbeidssokerregisteret-api"]
                  }
                },
                {
                  "requestParam": "scope",
                  "match": "default",
                  "claims": {
                    "aud": ["paw-arbeidssokerregisteret-api"]
                  }
                }
              ]
            }
          ]
        }
